version: "3"

services:
  loc-vung-admin:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PORT=${PORT}
